// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-wpYc7733xN3LTveJTewnqwG9H7FKgkw',
    appId: '1:168201112684:web:2761281adf6bd26a20dc49',
    messagingSenderId: '168201112684',
    projectId: 'spotify-clone-e0d8c',
    authDomain: 'spotify-clone-e0d8c.firebaseapp.com',
    storageBucket: 'spotify-clone-e0d8c.appspot.com',
    measurementId: 'G-5DW32Z4NBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpNNqmUiyaUVXCO786eNrvU_vMIevCPHo',
    appId: '1:168201112684:android:cf9582c0bbe708c820dc49',
    messagingSenderId: '168201112684',
    projectId: 'spotify-clone-e0d8c',
    storageBucket: 'spotify-clone-e0d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEGj8RSvmY3oqYWR5x0UifZF9vJ79fa2I',
    appId: '1:168201112684:ios:66a2097fe1acdf5220dc49',
    messagingSenderId: '168201112684',
    projectId: 'spotify-clone-e0d8c',
    storageBucket: 'spotify-clone-e0d8c.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEGj8RSvmY3oqYWR5x0UifZF9vJ79fa2I',
    appId: '1:168201112684:ios:66a2097fe1acdf5220dc49',
    messagingSenderId: '168201112684',
    projectId: 'spotify-clone-e0d8c',
    storageBucket: 'spotify-clone-e0d8c.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-wpYc7733xN3LTveJTewnqwG9H7FKgkw',
    appId: '1:168201112684:web:4de68ece9f4ee5e920dc49',
    messagingSenderId: '168201112684',
    projectId: 'spotify-clone-e0d8c',
    authDomain: 'spotify-clone-e0d8c.firebaseapp.com',
    storageBucket: 'spotify-clone-e0d8c.appspot.com',
    measurementId: 'G-JYDRPGM2J9',
  );
}
